version: "3.9"

services:
  discord-bot:
    container_name: gork-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        limits:
          memory: 256M